package com.git.bean;
// Generated 2017-10-12 15:02:16 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocumentCatalog generated by hbm2java
 */
public class DocumentCatalog  implements java.io.Serializable {


     private Long id;
     private String name;
     private Date date;
     private boolean flag;
     private Long authorId;
     private String authorName;
     private Integer type;
     private String content;
     private Integer order;
     private String address;
     private Set<DocumentCatalog> children = new HashSet<DocumentCatalog>(0);
     private Set<DocumentitemEntity> items = new HashSet<DocumentitemEntity>(0);
     private DocumentCatalog parent;

    public DocumentCatalog() {
    }

    public DocumentCatalog(String name, Date date, boolean flag, Long authorId, String authorName, Integer type, String content, Integer order, String address, Set<DocumentCatalog> children, Set<DocumentitemEntity> items, DocumentCatalog parent) {
       this.name = name;
       this.date = date;
       this.flag = flag;
       this.authorId = authorId;
       this.authorName = authorName;
       this.type = type;
       this.content = content;
       this.order = order;
       this.address = address;
       this.children = children;
       this.items = items;
       this.parent = parent;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public boolean isFlag() {
        return this.flag;
    }
    
    public void setFlag(boolean flag) {
        this.flag = flag;
    }
    public Long getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Integer getOrder() {
        return this.order;
    }
    
    public void setOrder(Integer order) {
        this.order = order;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set<DocumentCatalog> getChildren() {
        return this.children;
    }
    
    public void setChildren(Set<DocumentCatalog> children) {
        this.children = children;
    }
    public Set<DocumentitemEntity> getItems() {
        return this.items;
    }
    
    public void setItems(Set<DocumentitemEntity> items) {
        this.items = items;
    }
    public DocumentCatalog getParent() {
        return this.parent;
    }
    
    public void setParent(DocumentCatalog parent) {
        this.parent = parent;
    }




}


