package com.git.bean;
// Generated 2017-10-15 0:18:24 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * DocumentitemEntity generated by hbm2java
 */
public class DocumentitemEntity  implements java.io.Serializable {


     private Long id;
     private String name;
     private Long authorId;
     private String authorName;
     private Date date;
     private Integer realSize;
     private String size;
     private String randomName;
     private String type;
     private DocumentCatalog documentCatalog;

    public DocumentitemEntity() {
    }

	
    public DocumentitemEntity(Long authorId, Date date, Integer realSize, String size, String randomName, String type) {
        this.authorId = authorId;
        this.date = date;
        this.realSize = realSize;
        this.size = size;
        this.randomName = randomName;
        this.type = type;
    }
    public DocumentitemEntity(String name, Long authorId, String authorName, Date date, Integer realSize, String size, String randomName, String type, DocumentCatalog documentCatalog) {
       this.name = name;
       this.authorId = authorId;
       this.authorName = authorName;
       this.date = date;
       this.realSize = realSize;
       this.size = size;
       this.randomName = randomName;
       this.type = type;
       this.documentCatalog = documentCatalog;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Long getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getRealSize() {
        return this.realSize;
    }
    
    public void setRealSize(Integer realSize) {
        this.realSize = realSize;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getRandomName() {
        return this.randomName;
    }
    
    public void setRandomName(String randomName) {
        this.randomName = randomName;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public DocumentCatalog getDocumentCatalog() {
        return this.documentCatalog;
    }
    
    public void setDocumentCatalog(DocumentCatalog documentCatalog) {
        this.documentCatalog = documentCatalog;
    }




}


