package com.git.bean;
// Generated 2017-10-24 19:35:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Long id;
     private Long authorId;
     private String authorName;
     private Date date;
     private String content;
     private Topic parent;

    public Post() {
    }

    public Post(Long authorId, String authorName, Date date, String content, Topic parent) {
       this.authorId = authorId;
       this.authorName = authorName;
       this.date = date;
       this.content = content;
       this.parent = parent;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public Long getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public Topic getParent() {
        return this.parent;
    }
    
    public void setParent(Topic parent) {
        this.parent = parent;
    }




}


