package com.git.bean;
// Generated 2017-10-24 19:35:38 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Topic generated by hbm2java
 */
public class Topic  implements java.io.Serializable {


     private Long id;
     private String title;
     private Long content;
     private Long authorId;
     private String authorName;
     private Date date;
     private Long viewCount;
     private Long postCount;
     private Date lastDate;
     private String lastAuthor;
     private Set<Post> children = new HashSet<Post>(0);
     private Board parent;

    public Topic() {
    }

    public Topic(String title, Long content, Long authorId, String authorName, Date date, Long viewCount, Long postCount, Date lastDate, String lastAuthor, Set<Post> children, Board parent) {
       this.title = title;
       this.content = content;
       this.authorId = authorId;
       this.authorName = authorName;
       this.date = date;
       this.viewCount = viewCount;
       this.postCount = postCount;
       this.lastDate = lastDate;
       this.lastAuthor = lastAuthor;
       this.children = children;
       this.parent = parent;
    }
   
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Long getContent() {
        return this.content;
    }
    
    public void setContent(Long content) {
        this.content = content;
    }
    public Long getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Long authorId) {
        this.authorId = authorId;
    }
    public String getAuthorName() {
        return this.authorName;
    }
    
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Long getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }
    public Long getPostCount() {
        return this.postCount;
    }
    
    public void setPostCount(Long postCount) {
        this.postCount = postCount;
    }
    public Date getLastDate() {
        return this.lastDate;
    }
    
    public void setLastDate(Date lastDate) {
        this.lastDate = lastDate;
    }
    public String getLastAuthor() {
        return this.lastAuthor;
    }
    
    public void setLastAuthor(String lastAuthor) {
        this.lastAuthor = lastAuthor;
    }
    public Set<Post> getChildren() {
        return this.children;
    }
    
    public void setChildren(Set<Post> children) {
        this.children = children;
    }
    public Board getParent() {
        return this.parent;
    }
    
    public void setParent(Board parent) {
        this.parent = parent;
    }




}


